# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide
description: "My eval"

prompts:
  - file://eval_prompt.txt


providers:
  - "openai:gpt-4o-mini"
  - "openai:gpt-4o"
  - "openai:gpt-3.5-turbo"


defaultTest:
  assert:
    # Verify that the output doesn't contain "AI language model"
    - type: not-contains
      value: AI language model

    - type: llm-rubric
      value: Should mention all five products from the text.

    - type: latency
      threshold: 10000

    - type: llm-rubric
      value: Is using the input text to generate the new text.

    - type: select-best
      value: Select the best output based on the input text.

    - type: llm-rubric
      value: Does the generated output use the information about the company Shoby and its products?

    - type: python
      value: |
        diff = abs(500 - len(output.split(" ")))
        if diff < 100:
          return {
            'pass': True,
            'score': diff,
            'reason': 'The output length is between 400 to 600 words.'
          }
        else:
          return {
            'pass': False,
            'score': diff,
            'reason': 'The output length is not between 400 to 600 words.'
          }

